blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }

blog_socket:
    path:     /socket/
    defaults: { _controller: BlogBundle:Socket:index }

create_post:
    path:     /post/createPost/
    defaults: { _controller: BlogBundle:Post:createPost }

show_post:
    path:     /post/showPost/{id}
    defaults: { _controller: BlogBundle:Post:showPost }

delete_post:
    path:     /post/deletePost/{id}
    defaults: { _controller: BlogBundle:Post:deletePost }

update_post:
    path:     /post/updatePost/{id}
    defaults: { _controller: BlogBundle:Post:updatePost }

mybook_post:
    path:     /post/mybook
    defaults: { _controller: BlogBundle:Post:mybookPost }
