services:
#    blog.example:
#        class: BlogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    blog.registrationSuccess:
        class: BlogBundle\EventListener\RegistrationSuccessListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }
